apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cattle.io/timestamp: "2023-01-09T10:18:53Z"
      cni.projectcalico.org/podIP: 10.42.2.53/32
      cni.projectcalico.org/podIPs: 10.42.2.53/32
    creationTimestamp: "2023-01-09T10:26:01Z"
    generateName: jobmanager-76f58bbdc-
    labels:
      pod-template-hash: 76f58bbdc
      workload.user.cattle.io/workloadselector: apps.deployment-flink-jobmanager
    name: jobmanager-76f58bbdc-9zxdt
    namespace: flink
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: jobmanager-76f58bbdc
      uid: 2cd42d79-4284-4cff-8a0e-d7fb0048d79f
    resourceVersion: "3862498"
    uid: b9bf3969-446c-4c0a-8d4a-492fde14278d
  spec:
    affinity:
      podAffinity: {}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - jobmanager
            topologyKey: kubernetes.io/hostname
          weight: 100
    containers:
    - args:
      - jobmanager
      env:
      - name: JOB_MANAGER_RPC_ADDRESS
        value: jobmanager
      - name: FLINK_PROPERTIES
        value: 'env.java.opts: -Duser.timezone=Asia/Shanghai'
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      image: flink:1.13.5-scala_2.12-java8
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 60
        successThreshold: 1
        tcpSocket:
          port: 6123
        timeoutSeconds: 30
      name: container-0
      ports:
      - containerPort: 8081
        name: webui
        protocol: TCP
      - containerPort: 6123
        name: rpc
        protocol: TCP
      - containerPort: 6124
        name: blob-server
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/flink/lib
        name: vol-ighsr
        subPath: jar
      - mountPath: /opt/flink/conf/flink-conf.yaml
        name: vol-swpyw
        subPath: flink-conf.yaml
      - mountPath: /opt/flink/conf/log4j-console.properties
        name: vol-swpyw
        subPath: log4j-console.properties
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-7p648
        readOnly: true
    dnsConfig: {}
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostAliases:
    - hostnames:
      - master
      ip: 192.168.10.101
    - hostnames:
      - slave1
      ip: 192.168.10.102
    - hostnames:
      - slave2
      ip: 192.168.10.103
    nodeName: pdl2-2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: flink-conf
      name: vol-swpyw
    - name: vol-ighsr
      persistentVolumeClaim:
        claimName: pvc-flink
    - name: default-token-7p648
      secret:
        defaultMode: 420
        secretName: default-token-7p648
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-01-09T10:26:01Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-01-09T10:26:02Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-01-09T10:26:02Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-01-09T10:26:01Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://ac431d0f374e8ecd8a51416eeec57cf7348100c9d96a4e93f04cc156334f026d
      image: flink:1.13.5-scala_2.12-java8
      imageID: docker-pullable://flink@sha256:228fbb252d3f33bacef09af6144e4ff6a49c4c871c75df014c66536d596fdc0c
      lastState: {}
      name: container-0
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-01-09T10:26:01Z"
    hostIP: 192.168.10.102
    phase: Running
    podIP: 10.42.2.53
    podIPs:
    - ip: 10.42.2.53
    qosClass: BestEffort
    startTime: "2023-01-09T10:26:01Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cattle.io/timestamp: "2023-01-10T01:43:09Z"
      cni.projectcalico.org/podIP: 10.42.2.54/32
      cni.projectcalico.org/podIPs: 10.42.2.54/32
    creationTimestamp: "2023-01-10T01:43:09Z"
    generateName: taskmanager-5678cc5c59-
    labels:
      pod-template-hash: 5678cc5c59
      workload.user.cattle.io/workloadselector: apps.deployment-flink-taskmanager
    name: taskmanager-5678cc5c59-b8cg9
    namespace: flink
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: taskmanager-5678cc5c59
      uid: 1da59611-33da-428e-b0af-76f28b1b4a45
    resourceVersion: "4002957"
    uid: fdcb4624-e54f-4212-a4cc-b6d5556de217
  spec:
    affinity:
      podAffinity: {}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - taskmanager
            topologyKey: kubernetes.io/hostname
          weight: 100
    containers:
    - args:
      - taskmanager
      env:
      - name: JOB_MANAGER_RPC_ADDRESS
        value: jobmanager
      - name: FLINK_PROPERTIES
        value: 'env.java.opts: -Duser.timezone=Asia/Shanghai'
      image: flink:1.13.5-scala_2.12-java8
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 60
        successThreshold: 1
        tcpSocket:
          port: 6122
        timeoutSeconds: 30
      name: container-0
      ports:
      - containerPort: 6122
        name: rpc
        protocol: TCP
      - containerPort: 6125
        name: query-state
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/flink/lib
        name: vol-0rxui
        subPath: jar
      - mountPath: /opt/flink/conf/flink-conf.yaml
        name: vol-grczo
        subPath: flink-conf.yaml
      - mountPath: /opt/flink/conf/log4j-console.properties
        name: vol-grczo
        subPath: log4j-console.properties
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-7p648
        readOnly: true
    dnsConfig: {}
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostAliases:
    - hostnames:
      - master
      ip: 192.168.10.101
    - hostnames:
      - slave1
      ip: 192.168.10.102
    - hostnames:
      - slave2
      ip: 192.168.10.103
    nodeName: pdl2-2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: flink-conf
      name: vol-grczo
    - name: vol-0rxui
      persistentVolumeClaim:
        claimName: pvc-flink
    - name: default-token-7p648
      secret:
        defaultMode: 420
        secretName: default-token-7p648
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T01:43:09Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T01:43:10Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T01:43:10Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T01:43:09Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://970d7ef22239313bf78b1d23f4f7cbb5a56b080a9c4249e5ff84dc535bccf592
      image: flink:1.13.5-scala_2.12-java8
      imageID: docker-pullable://flink@sha256:228fbb252d3f33bacef09af6144e4ff6a49c4c871c75df014c66536d596fdc0c
      lastState: {}
      name: container-0
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-01-10T01:43:10Z"
    hostIP: 192.168.10.102
    phase: Running
    podIP: 10.42.2.54
    podIPs:
    - ip: 10.42.2.54
    qosClass: BestEffort
    startTime: "2023-01-10T01:43:09Z"
kind: List
metadata:
  resourceVersion: ""
