apiVersion: v1
items:
- apiVersion: v1
  data:
    flink-conf.yaml: |-
      jobmanager.rpc.address: jobmanager
      jobmanager.rpc.port: 6123
      # jobmanager.memory.process.size: 3500m
      jobmanager.memory.jvm-metaspace.size: 2048m
      jobmanager.execution.failover-strategy: region
      jobmanager.memory.heap.size: 2048m

      taskmanager.rpc.port: 6122
      taskmanager.memory.process.size: 16384m
      #taskmanager.memory.jvm-metaspace.size: 2048m
      taskmanager.numberOfTaskSlots: 40

      parallelism.default: 1
      blob.server.port: 6124
      query.server.port: 6125
      env.java.opts.taskmanager: "-Duser.timezone=Asia/Shanghai"
      akka.ask.timeout: 60s
      akka.framesize: "104857600b"
      web.timeout: 1000000
      rest.bind-address: 0.0.0.0
      heartbeat.timeout: 180000
      classloader.resolve-order: parent-first
      classloader.check-leaked-classloader: false

      # HA
      high-availability: zookeeper
      high-availability.zookeeper.quorum: 192.168.3.204:2181
      high-availability.cluster-id: /pdl2
      high-availability.zookeeper.path.root: /flink


      # hdfs
      high-availability.storageDir: hdfs://hdfs-master.hadoop:9000/flink/recovery
      #high-availability.storageDir: /opt/flink/recovery
      restart-strategy: fixed-delay
      restart-strategy.fixed-delay.attempts: 10

      # checkpoint
      state.backend: filesystem
      # state.backend.incremental: true
      state.checkpoint-storage: filesystem
      state.checkpoints.dir: hdfs://hdfs-master.hadoop:9000/flink/checkpoints
      state.savepoints.dir: hdfs://hdfs-master.hadoop:9000/flink/savepoints


      # state.backend.rocksdb.localdir: /opt/flink/checkpoints
      # state.backend.rocksdb.timer-service.factory: HEAP

      web.upload.dir: /opt/flink/joblib
    log4j-console.properties: |-
      # This affects logging for both user code and Flink
      rootLogger.level = INFO
      rootLogger.appenderRef.console.ref = ConsoleAppender
      rootLogger.appenderRef.rolling.ref = RollingFileAppender

      # Uncomment this if you want to _only_ change Flink's logging
      #logger.flink.name = org.apache.flink
      #logger.flink.level = INFO

      # The following lines keep the log level of common libraries/connectors on
      # log level INFO. The root logger does not override this. You have to manually
      # change the log levels here.
      logger.akka.name = akka
      logger.akka.level = INFO
      logger.kafka.name= org.apache.kafka
      logger.kafka.level = INFO
      logger.hadoop.name = org.apache.hadoop
      logger.hadoop.level = INFO
      logger.zookeeper.name = org.apache.zookeeper
      logger.zookeeper.level = INFO

      # Log all infos to the console
      appender.console.name = ConsoleAppender
      appender.console.type = CONSOLE
      appender.console.layout.type = PatternLayout
      appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

      # Log all infos in the given rolling file
      appender.rolling.name = RollingFileAppender
      appender.rolling.type = RollingFile
      appender.rolling.append = false
      appender.rolling.fileName = ${sys:log.file}
      appender.rolling.filePattern = ${sys:log.file}.%i
      appender.rolling.layout.type = PatternLayout
      appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
      appender.rolling.policies.type = Policies
      appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
      appender.rolling.policies.size.size=100MB
      appender.rolling.strategy.type = DefaultRolloverStrategy
      appender.rolling.strategy.max = 10

      # Suppress the irrelevant (wrong) warnings from the Netty channel handler
      logger.netty.name = org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline
      logger.netty.level = OFF
  kind: ConfigMap
  metadata:
    creationTimestamp: "2022-12-27T08:26:10Z"
    name: flink-conf
    namespace: flink
    resourceVersion: "15386774"
    uid: 4e6fb301-05c0-45ed-b99e-43b48b64f031
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIC4TCCAcmgAwIBAgIBADANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDEwdrdWJl
      LWNhMB4XDTIyMTIxNjAxMTc1OFoXDTMyMTIxMzAxMTc1OFowEjEQMA4GA1UEAxMH
      a3ViZS1jYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALnKg8ituiWe
      95bePLO6cRVh3aOjbM4tVTGKpFR4g8Zc3QfF/opCoDsZrnx08Q9kf80lD0mSCvo1
      U6tUVeBn4UIzvlxGcv5yRdVJ6c8n82Hwo0pU6sYKLQadT+Db5e/eTqPehls5sNma
      cuqueG/OSTVfr6ogZO4YEBwYnDNfCSPgLjALo6NLJwyDdwP+wyK3OD5FD7Bmv38U
      yWZ7UPM7qyTqipbgKvbUfDB1VuRYZyOk7TmFH6w9XdneFiY/vss6q+3scXX1HS4c
      eI0lE7Y4O1h00cz7St+F9Pp3CTJ5bLTagGC8N5ejXafb3cL9Pjx8bsRABcm+n2mX
      7Ztdykg4g4sCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMB
      Af8wHQYDVR0OBBYEFMRVKnrflDLoT9F+8oDCdh9EV8eKMA0GCSqGSIb3DQEBCwUA
      A4IBAQBBpyROOmN1CXR18JkncbblhozUSsl8ghwYkI+4QXbnTGbzv97RkuYntjsq
      2gjxbaElrTxWVWGQzQrZ+X4qzyn6BGltwbvCdYHRSLN/6G4eebF2oglAFSZEo5hb
      hYwC9VEomBkHo1EVHzsAmeqoHUhO1hFEs04asx5XiFSbglg4Vjv/1u+QqTx8dlvX
      EpgbP7W0TccI1tikQRoIa+BxJOQXZuXOZxdM2a3Lq+DlAOW9ld+j2P5L+DlHaBdx
      gwwFJ59oh/Ce7qr5RFukrSd1/6r6BnvcEHWkpdfzgYMUVyoBXoI9giJhy3umi9Fk
      wadXCKkA/h9z3O9UdYkhFnnt7alu
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2022-12-23T09:18:14Z"
    name: kube-root-ca.crt
    namespace: flink
    resourceVersion: "1603327"
    uid: 2ae13e14-5347-489b-a5be-37affddbe426
- apiVersion: v1
  data:
    address: akka.tcp://flink@10.42.2.59:6123/user/rpc/dispatcher_1
    sessionId: d3932356-db52-4292-b786-ffa680b11851
  kind: ConfigMap
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"f9314352-95b7-43f1-bf20-385d379cbaf3","leaseDuration":15.000000000,"acquireTime":"2023-02-06T06:55:27.923000Z","renewTime":"2023-02-06T07:54:07.946000Z","leaderTransitions":705}'
    creationTimestamp: "2023-02-06T06:09:44Z"
    labels:
      app: pdl2
      configmap-type: high-availability
      type: flink-native-kubernetes
    name: pdl2-dispatcher-leader
    namespace: flink
    resourceVersion: "11664481"
    uid: 5521e552-6c12-4739-91c1-75d3c5c8fdd1
- apiVersion: v1
  data:
    address: akka.tcp://flink@10.42.2.59:6123/user/rpc/resourcemanager_0
    sessionId: b61ae446-3901-4f2c-a117-e222be8d66e1
  kind: ConfigMap
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"f9314352-95b7-43f1-bf20-385d379cbaf3","leaseDuration":15.000000000,"acquireTime":"2023-02-06T06:55:27.592000Z","renewTime":"2023-02-06T07:54:07.634000Z","leaderTransitions":705}'
    creationTimestamp: "2023-02-06T06:09:44Z"
    labels:
      app: pdl2
      configmap-type: high-availability
      type: flink-native-kubernetes
    name: pdl2-resourcemanager-leader
    namespace: flink
    resourceVersion: "11664454"
    uid: e9018958-8180-48ae-a0e8-21f768a57c20
- apiVersion: v1
  data:
    address: http://10.42.2.59:8081
    sessionId: a8d29f26-e3b1-4afe-b475-7b10912d8fa1
  kind: ConfigMap
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"f9314352-95b7-43f1-bf20-385d379cbaf3","leaseDuration":15.000000000,"acquireTime":"2023-02-06T06:55:39.031000Z","renewTime":"2023-02-06T07:54:09.059000Z","leaderTransitions":703}'
    creationTimestamp: "2023-02-06T06:09:44Z"
    labels:
      app: pdl2
      configmap-type: high-availability
      type: flink-native-kubernetes
    name: pdl2-restserver-leader
    namespace: flink
    resourceVersion: "11664494"
    uid: c84e949f-74f5-488d-bb33-2c3129904ae3
kind: List
metadata:
  resourceVersion: ""
