apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "17"
      field.cattle.io/description: kafka
    creationTimestamp: "2022-12-16T08:54:39Z"
    generation: 25
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-kafka-kafka
    name: kafka
    namespace: kafka
    resourceVersion: "15394316"
    uid: 6a63bf66-693e-49bc-bf48-7305fc8623c3
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-kafka-kafka
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2023-02-13T09:39:55Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-kafka-kafka
      spec:
        affinity: {}
        containers:
        - env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka.kafka:9092
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://0.0.0.0:9092
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper.zookeeper:2181
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          image: bitnami/kafka:3.3.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9092
            timeoutSeconds: 1
          name: container-0
          ports:
          - containerPort: 9092
            name: kafka
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9092
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-16T08:54:39Z"
      lastUpdateTime: "2023-02-13T09:40:22Z"
      message: ReplicaSet "kafka-6898dd8fc5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-02-23T04:07:32Z"
      lastUpdateTime: "2023-02-23T04:07:32Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 25
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
