apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["kafka/kafka"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-16T08:54:39Z"
    name: kafka
    namespace: kafka
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: kafka
      uid: 6a63bf66-693e-49bc-bf48-7305fc8623c3
    resourceVersion: "3811963"
    uid: 70642990-e414-4742-b22c-2534136cba13
  spec:
    clusterIP: 10.43.168.225
    clusterIPs:
    - 10.43.168.225
    externalIPs:
    - 192.168.3.204
    ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-kafka-kafka
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
