apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cattle.io/timestamp: "2022-12-21T02:13:33Z"
      cni.projectcalico.org/podIP: 10.42.2.55/32
      cni.projectcalico.org/podIPs: 10.42.2.55/32
    creationTimestamp: "2023-01-10T08:09:43Z"
    generateName: dubbo-8d87d88c8-
    labels:
      pod-template-hash: 8d87d88c8
      workload.user.cattle.io/workloadselector: apps.deployment-dubbo-dubbo
    name: dubbo-8d87d88c8-l8tpg
    namespace: dubbo
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: dubbo-8d87d88c8
      uid: 6a6c639e-8cba-4742-b7b7-434beb1a4fb6
    resourceVersion: "4061993"
    uid: 21a36901-a387-4f84-9518-5eb4d4b1322f
  spec:
    affinity: {}
    containers:
    - env:
      - name: admin.registry.address
        value: zookeeper://zookeeper.zookeeper:2181
      - name: admin.config-center
        value: zookeeper://zookeeper.zookeeper:2181
      - name: admin.metadata-report.address
        value: zookeeper://zookeeper.zookeeper:2181
      image: apache/dubbo-admin:0.5.0
      imagePullPolicy: IfNotPresent
      name: container-0
      ports:
      - containerPort: 8080
        name: dubbo
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-m6q7d
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: pdl2-2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-m6q7d
      secret:
        defaultMode: 420
        secretName: default-token-m6q7d
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T08:09:43Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T08:10:22Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T08:10:22Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-01-10T08:09:43Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://cc49d759085e15fddcf6ef7f15f2149110677ad1d630c7998644a3093538edb5
      image: apache/dubbo-admin:0.5.0
      imageID: docker-pullable://apache/dubbo-admin@sha256:adb05de9c0f91d52f7355a6b5c39a6698df3103eb3c1cf148f41ba542b9cdaeb
      lastState: {}
      name: container-0
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-01-10T08:10:21Z"
    hostIP: 192.168.10.102
    phase: Running
    podIP: 10.42.2.55
    podIPs:
    - ip: 10.42.2.55
    qosClass: BestEffort
    startTime: "2023-01-10T08:09:43Z"
kind: List
metadata:
  resourceVersion: ""
