apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "8"
      field.cattle.io/description: dubbo-admin
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.3.204"],"port":30888,"protocol":"TCP","serviceName":"dubbo:dubbo-nodeport","allNodes":true}]'
    creationTimestamp: "2022-12-19T09:53:08Z"
    generation: 9
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-dubbo-dubbo
    name: dubbo
    namespace: dubbo
    resourceVersion: "10726853"
    uid: bf14733a-1fe5-4ac3-b7f2-b53d5c9e6379
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-dubbo-dubbo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2023-02-03T03:19:45Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-dubbo-dubbo
      spec:
        affinity: {}
        containers:
        - env:
          - name: admin.registry.address
            value: zookeeper://zookeeper.zookeeper:2181
          - name: admin.config-center
            value: zookeeper://zookeeper.zookeeper:2181
          - name: admin.metadata-report.address
            value: zookeeper://zookeeper.zookeeper:2181
          image: apache/dubbo-admin:0.5.0
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 8080
            name: dubbo
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-01-06T07:31:53Z"
      lastUpdateTime: "2023-01-06T07:31:53Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-19T09:53:08Z"
      lastUpdateTime: "2023-02-03T03:21:11Z"
      message: ReplicaSet "dubbo-7684467854" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 9
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
