apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-app
    namespace: default
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: pv-app
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
kind: List
