apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: presto
    namespace: presto
  spec:
    ports:
    - name: presto
      port: 8091
      protocol: TCP
      targetPort: 8091
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-presto-presto
    sessionAffinity: None
    type: ClusterIP
kind: List
