apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: dubbo
    namespace: dubbo
  spec:
    ports:
    - name: dubbo
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-dubbo-dubbo
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: dubbo-nodeport
    namespace: dubbo
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: dubbo
      nodePort: 30888
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-dubbo-dubbo
    sessionAffinity: None
    type: NodePort
kind: List
