apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "9"
      field.cattle.io/publicEndpoints: "null"
    creationTimestamp: "2022-12-27T05:11:32Z"
    generation: 11
    labels:
      app: mysql
      workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql
    name: mysql
    namespace: mysql
    resourceVersion: "10749134"
    uid: e8fd31c5-d809-409a-a059-eacb5524c997
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2022-12-30T05:37:59Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql
      spec:
        affinity: {}
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          image: mysql:5.7.40
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: 200m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/mysql/my.cnf
            name: vol-tqqvl
            subPath: my.cnf
          - mountPath: /var/lib/mysql
            name: vol-4stms
            subPath: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: mysql
          name: vol-tqqvl
        - name: vol-4stms
          persistentVolumeClaim:
            claimName: pvc-mysql
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-01-06T07:32:08Z"
      lastUpdateTime: "2023-01-06T07:32:08Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-27T05:11:32Z"
      lastUpdateTime: "2023-02-03T05:03:45Z"
      message: ReplicaSet "mysql-7659bd574" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 11
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "27"
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.3.204"],"port":30336,"protocol":"TCP","serviceName":"mysql:mysql8-nodeport","allNodes":true}]'
    creationTimestamp: "2022-12-28T06:58:26Z"
    generation: 38
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql8
    name: mysql8
    namespace: mysql
    resourceVersion: "10745204"
    uid: 7b90a388-2efc-422c-87a0-484052177e40
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql8
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2023-02-02T09:23:07Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql8
      spec:
        affinity: {}
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          image: mysql:8.0.22
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 3306
            name: mysql8
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: 200m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: vol-ztspl
            subPath: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: mysql8
          name: vol-px23x
        - name: vol-ztspl
          persistentVolumeClaim:
            claimName: pvc-mysql8
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-02-02T10:10:29Z"
      lastUpdateTime: "2023-02-02T10:10:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-28T06:58:26Z"
      lastUpdateTime: "2023-02-03T04:46:35Z"
      message: ReplicaSet "mysql8-7c5cdb8bf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 38
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
