apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-hadoop
    namespace: hadoop
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
    volumeName: pv-hadoop
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
kind: List
