apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: hadoop-datanode
      workload.user.cattle.io/workloadselector: apps.statefulset-hadoop-datanode
    name: datanode
    namespace: hadoop
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.statefulset-hadoop-datanode
    serviceName: datanode
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.statefulset-hadoop-datanode
      spec:
        affinity:
          podAffinity: {}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - hadoop-datanode
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: HADOOP_NODE_TYPE
            value: datanode
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                key: HDFS_MASTER_SERVICE
                name: hadoop-conf
                optional: false
          - name: HDOOP_YARN_MASTER
            valueFrom:
              configMapKeyRef:
                key: HDOOP_YARN_MASTER
                name: hadoop-conf
                optional: false
          image: 192.168.10.101:5000/hadoop:3.3.4
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 9867
            name: ipc
            protocol: TCP
          - containerPort: 9866
            name: data-transfer
            protocol: TCP
          - containerPort: 9865
            name: https
            protocol: TCP
          - containerPort: 9864
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/hadoop-env.sh
            name: vol-hadoop-conf
            subPath: hadoop-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-hadoop-conf
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-hadoop-conf
            subPath: hdfs-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            name: vol-hadoop-conf
            subPath: yarn-site.xml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-hadoop-conf
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: hadoop-yarnnode
      workload.user.cattle.io/workloadselector: apps.statefulset-hadoop-yarn-node
    name: yarn-node
    namespace: hadoop
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.statefulset-hadoop-yarn-node
    serviceName: yarnnode
    template:
      metadata:
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.statefulset-hadoop-yarn-node
      spec:
        affinity:
          podAffinity: {}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - hadoop-yarnnode
                namespaces:
                - hadoop
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: HADOOP_NODE_TYPE
            value: yarnnode
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                key: HDFS_MASTER_SERVICE
                name: hadoop-conf
                optional: false
          - name: HDOOP_YARN_MASTER
            valueFrom:
              configMapKeyRef:
                key: HDOOP_YARN_MASTER
                name: hadoop-conf
                optional: false
          image: 192.168.10.101:5000/hadoop:3.3.4
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 8040
            name: localizer
            protocol: TCP
          - containerPort: 8041
            name: webapp
            protocol: TCP
          - containerPort: 8042
            name: nm-cm
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/hadoop-env.sh
            name: vol-hadoop-conf
            subPath: hadoop-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-hadoop-conf
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-hadoop-conf
            subPath: hdfs-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            name: vol-hadoop-conf
            subPath: yarn-site.xml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-hadoop-conf
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
kind: List
