apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-hadoop
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: pvc-hadoop
      namespace: hadoop
    nfs:
      path: /data/pv/hadoop
      server: 192.168.10.101
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
kind: List
