apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-hadoop-hdfs-master
    name: hdfs-master
    namespace: hadoop
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-hadoop-hdfs-master
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-hadoop-hdfs-master
      spec:
        affinity: {}
        containers:
        - env:
          - name: HADOOP_NODE_TYPE
            value: namenode
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                key: HDFS_MASTER_SERVICE
                name: hadoop-conf
                optional: false
          - name: HDOOP_YARN_MASTER
            valueFrom:
              configMapKeyRef:
                key: HDOOP_YARN_MASTER
                name: hadoop-conf
                optional: false
          image: 192.168.10.101:5000/hadoop:3.3.4
          imagePullPolicy: Always
          name: container-0
          ports:
          - containerPort: 9000
            name: default-fs
            protocol: TCP
          - containerPort: 9870
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/hadoop-env.sh
            name: vol-hadoop-conf
            subPath: hadoop-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-hadoop-conf
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-hadoop-conf
            subPath: hdfs-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            name: vol-hadoop-conf
            subPath: yarn-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/rack_topology.data
            name: vol-hadoop-conf
            subPath: rack_topology.data
          - mountPath: /opt/hadoop/hdfs/name
            name: vol-hadoop
            subPath: name
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-hadoop-conf
        - name: vol-hadoop
          persistentVolumeClaim:
            claimName: pvc-hadoop
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-hadoop-yarn-master
    name: yarn-master
    namespace: hadoop
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-hadoop-yarn-master
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-hadoop-yarn-master
      spec:
        affinity: {}
        containers:
        - env:
          - name: HADOOP_NODE_TYPE
            value: resourceman
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                key: HDFS_MASTER_SERVICE
                name: hadoop-conf
                optional: false
          - name: HDOOP_YARN_MASTER
            valueFrom:
              configMapKeyRef:
                key: HDOOP_YARN_MASTER
                name: hadoop-conf
                optional: false
          image: 192.168.10.101:5000/hadoop:3.3.4
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 8031
            name: ipc1
            protocol: TCP
          - containerPort: 8033
            name: ipc2
            protocol: TCP
          - containerPort: 8088
            name: http
            protocol: TCP
          - containerPort: 8032
            name: rm-asm
            protocol: TCP
          - containerPort: 8030
            name: ipc-scheduler
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/hadoop-env.sh
            name: vol-hadoop-conf
            subPath: hadoop-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-hadoop-conf
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-hadoop-conf
            subPath: hdfs-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            name: vol-hadoop-conf
            subPath: yarn-site.xml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-hadoop-conf
kind: List
