apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: kafka
    namespace: kafka
  spec:
    ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-kafka-kafka
    sessionAffinity: None
    type: ClusterIP
kind: List
