apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["xxl-job/xxl-job-admin"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-26T09:58:54Z"
    name: xxl-job-admin
    namespace: xxl-job
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: xxl-job-admin
      uid: 271e2442-b6f0-404a-a188-cc3c330b1c8d
    resourceVersion: "8552054"
    uid: 9f652156-59f0-41a8-a058-1071342cfcee
  spec:
    clusterIP: 10.43.215.123
    clusterIPs:
    - 10.43.215.123
    externalIPs:
    - 192.168.3.204
    ports:
    - name: xxl-admin
      port: 30405
      protocol: TCP
      targetPort: 30405
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-xxl-job-xxl-job-admin
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
