apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: redis
    namespace: redis
  spec:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-redis-redis
    sessionAffinity: None
    type: ClusterIP
kind: List
