apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "8"
      field.cattle.io/description: redis server
    creationTimestamp: "2022-12-16T05:38:30Z"
    generation: 8
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-redis-redis
    name: redis
    namespace: redis
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-redis-redis
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-redis-redis
      spec:
        affinity: {}
        containers:
        - name: redis
          image: redis:6.2.4
          imagePullPolicy: IfNotPresent
          command: ["redis-server", "/etc/redis/redis.conf"]
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
          resources:
            limits:
              cpu: 1m
              memory: 1Gi
            requests:
              cpu: 1m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: vol-redis-data
          - mountPath: /etc/redis/redis.conf
            name: vol-redis
            subPath: redis.conf
          workingDir: /data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: vol-redis-data
          persistentVolumeClaim:
            claimName: pvc-redis
        - configMap:
            defaultMode: 420
            name: redis-conf
          name: vol-redis
kind: List
metadata:
  resourceVersion: ""
