apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      field.cattle.io/description: redis
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2022-12-16T04:45:36Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: pv-redis
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: pvc-redis
      namespace: redis
    nfs:
      path: /data/pv/redis
      server: 192.168.10.101
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
kind: List
