apiVersion: v1
items:
- apiVersion: v1
  data:
    redis.conf: |-
      appendonly yes
      cluster-enabled no
      dir /data/redis
      requirepass 123456
      port 6379
  kind: ConfigMap
  metadata:
    name: redis-conf
    namespace: redis
kind: List
metadata:
  resourceVersion: ""
