
linux:
  host: 192.168.3.204
  port: 22
  username: root
  password: '123456'


mysql:
  host: 192.168.3.164
  port: 30362
  database: '0928'
  username: zeusroot
  password: zhanwanzhanchi

k8s:
  command: https://192.168.3.204:6443/api/v1/namespaces/flink/pods









