FROM python:3-slim

RUN pip install -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com PyMySQL==0.9.3
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple PyYAML==5.1
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple paramiko==2.12.0
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple kubernetes

ADD main.py /

CMD ["python", "/main.py"]
