apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/data-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T02:53:14Z"
    name: data-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: data-server
      uid: 73d35368-c377-4b7b-b03d-4eed898e8533
    resourceVersion: "2677445"
    uid: 09f68ac4-17c1-4d48-8544-e22452715f84
  spec:
    clusterIP: 10.43.133.188
    clusterIPs:
    - 10.43.133.188
    ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-data-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/frontweb"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T07:26:08Z"
    name: frontweb
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: frontweb
      uid: 8f8682c5-112a-4568-a62f-d2c8a4f9df43
    resourceVersion: "2699970"
    uid: ae98fc08-9b51-4dc4-90dc-6fb6694438e8
  spec:
    clusterIP: 10.43.24.142
    clusterIPs:
    - 10.43.24.142
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-frontweb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.3.204"],"port":30080,"protocol":"TCP","serviceName":"default:frontweb-nodeport","allNodes":true}]'
      field.cattle.io/targetWorkloadIds: '["default/frontweb"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T07:26:08Z"
    name: frontweb-nodeport
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: frontweb
      uid: 8f8682c5-112a-4568-a62f-d2c8a4f9df43
    resourceVersion: "2699985"
    uid: 2d242aa8-533d-477d-a3e2-d8cdf6d31e94
  spec:
    clusterIP: 10.43.148.114
    clusterIPs:
    - 10.43.148.114
    externalTrafficPolicy: Cluster
    ports:
    - name: web
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-frontweb
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/integration-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T05:02:39Z"
    name: integration-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: integration-server
      uid: b826fc72-956e-45b4-bb4f-e2f002c7dfab
    resourceVersion: "2676642"
    uid: 1d1a8d6b-8fe8-4fa9-9f3b-523632cb1e98
  spec:
    clusterIP: 10.43.162.192
    clusterIPs:
    - 10.43.162.192
    ports:
    - name: tcp-8020
      port: 8020
      protocol: TCP
      targetPort: 8020
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-integration-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-12-16T01:21:32Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "189"
    uid: d140df37-93a7-4899-ac1b-803ea5b52a37
  spec:
    clusterIP: 10.43.0.1
    clusterIPs:
    - 10.43.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/lake-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T03:03:03Z"
    name: lake-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: lake-server
      uid: da714c55-ddf4-4db3-bfc6-c337dc6b6200
    resourceVersion: "2676036"
    uid: 7ee126b8-d980-449b-b9d4-4a9ba212282f
  spec:
    clusterIP: 10.43.44.170
    clusterIPs:
    - 10.43.44.170
    ports:
    - name: tcp-8050
      port: 8050
      protocol: TCP
      targetPort: 8050
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-lake-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/metadata-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T04:54:20Z"
    name: metadata-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: metadata-server
      uid: e13f98dc-e7db-43c6-9e74-86f16851abb1
    resourceVersion: "2675175"
    uid: eed37e48-244c-4d5a-ad1c-bc91b21e6735
  spec:
    clusterIP: 10.43.53.202
    clusterIPs:
    - 10.43.53.202
    ports:
    - name: tcp-8070
      port: 8070
      protocol: TCP
      targetPort: 8070
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-metadata-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/modeling-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T04:49:44Z"
    name: modeling-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: modeling-server
      uid: 96243430-331d-44c9-968e-bafcae37e0db
    resourceVersion: "2674229"
    uid: 669f0580-d7cd-4a72-ae8d-58711b8e3cab
  spec:
    clusterIP: 10.43.160.104
    clusterIPs:
    - 10.43.160.104
    ports:
    - name: tcp-8040
      port: 8040
      protocol: TCP
      targetPort: 8040
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-modeling-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/rest-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T03:10:10Z"
    name: rest-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: rest-server
      uid: 7855393c-bba7-49fd-9ff6-456a62b2af3f
    resourceVersion: "2656471"
    uid: 36f50adf-c289-406d-a597-dd645178498c
  spec:
    clusterIP: 10.43.123.121
    clusterIPs:
    - 10.43.123.121
    ports:
    - name: tcp-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-rest-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.3.204"],"port":30800,"protocol":"TCP","serviceName":"default:rest-server-nodeport","allNodes":true}]'
      field.cattle.io/targetWorkloadIds: '["default/rest-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2023-02-09T10:07:45Z"
    name: rest-server-nodeport
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: rest-server
      uid: 7855393c-bba7-49fd-9ff6-456a62b2af3f
    resourceVersion: "12363512"
    uid: 5a669134-2b67-42be-a0c6-c444d53a7ad0
  spec:
    clusterIP: 10.43.85.247
    clusterIPs:
    - 10.43.85.247
    externalTrafficPolicy: Cluster
    ports:
    - name: tcp-8000
      nodePort: 30800
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-rest-server
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/source-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T04:04:15Z"
    name: source-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: source-server
      uid: 84c95198-08d8-41bf-bbe2-8ba7ada53d64
    resourceVersion: "2666449"
    uid: 3c57f2d1-0696-437b-9d0c-2c6227978fb5
  spec:
    clusterIP: 10.43.174.36
    clusterIPs:
    - 10.43.174.36
    ports:
    - name: tcp-8030
      port: 8030
      protocol: TCP
      targetPort: 8030
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-source-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["default/user-server"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T03:59:02Z"
    name: user-server
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: user-server
      uid: b5abd455-ecd0-47d2-bc71-e97f88e59c41
    resourceVersion: "2665389"
    uid: 1eeb877e-e0f0-4fcf-8349-a09ef54f8d4f
  spec:
    clusterIP: 10.43.74.15
    clusterIPs:
    - 10.43.74.15
    ports:
    - name: tcp-8010
      port: 8010
      protocol: TCP
      targetPort: 8010
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-default-user-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
