apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["hive/hiveserver2"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-28T06:27:53Z"
    name: hiveserver2
    namespace: hive
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: hiveserver2
      uid: 00e06b12-6363-48d7-a1c8-2636e1bca15b
    resourceVersion: "2690842"
    uid: f615d2f1-be70-4e75-9b0b-e5faced08fb1
  spec:
    clusterIP: 10.43.95.21
    clusterIPs:
    - 10.43.95.21
    ports:
    - name: hiveserver2
      port: 10000
      protocol: TCP
      targetPort: 10000
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-hive-hiveserver2
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["hive/metastore"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-23T06:20:08Z"
    name: metastore
    namespace: hive
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: metastore
      uid: 3bda8f45-7a5b-456b-b77d-d8991387e1f0
    resourceVersion: "1575031"
    uid: 67901a7f-c0e1-4c17-9128-b668738a7acd
  spec:
    clusterIP: 10.43.210.157
    clusterIPs:
    - 10.43.210.157
    ports:
    - name: metastore
      port: 9083
      protocol: TCP
      targetPort: 9083
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-hive-metastore
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
