apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-xxl-job-xxl-job
    name: xxl-job
    namespace: xxl-job
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-xxl-job-xxl-job
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-xxl-job-xxl-job
      spec:
        affinity: {}
        containers:
        - env:
          - name: EXEC_MODE
            value: admin
          image: 10.168.2.90/sjzt/xxljob-executor-server:20230220163520
          imagePullPolicy: Always
          name: container-0
          ports:
          - containerPort: 30405
            hostIP: 192.168.3.204
            hostPort: 30405
            name: xxl-admin
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/java/config/application-admin.properties
            name: vol-admin-conf
            subPath: application.properties
          - mountPath: /data/java/config/application-executor.properties
            name: vol-executor-conf
            subPath: application.properties
        - env:
          - name: EXEC_MODE
            value: executor
          image: 10.168.2.90/sjzt/xxljob-executor-server:20230221114843
          imagePullPolicy: Always
          name: container-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/java/config/application-executor.properties
            name: vol-executor-conf
            subPath: application.properties
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: admin-conf
          name: vol-admin-conf
        - configMap:
            defaultMode: 420
            name: executor-conf
          name: vol-executor-conf
kind: List
