apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      field.cattle.io/description: mysql
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    name: pv-mysql
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 50Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: pvc-mysql
      namespace: mysql
    nfs:
      path: /data/pv/mysql
      server: 192.168.10.101
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    name: pv-mysql8
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: pvc-mysql8
      namespace: mysql
    nfs:
      path: /data/pv/mysql8
      server: 192.168.10.101
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
kind: List
