apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-mysql
    namespace: mysql
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 50Gi
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: pv-mysql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-mysql8
    namespace: mysql
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: pv-mysql8
kind: List
