apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: mysql
    namespace: mysql
  spec:
    ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: mysql8
    namespace: mysql
  spec:
    ports:
    - name: mysql8
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql8
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: mysql8-nodeport
    namespace: mysql
  spec:
    ports:
    - name: mysql8
      nodePort: 30336
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-mysql-mysql8
    sessionAffinity: None
    type: NodePort
kind: List
