apiVersion: v1
items:
- apiVersion: v1
  data:
    core-site.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <?xml-stylesheet
      type=\"text/xsl\" href=\"configuration.xsl\" rel=\"external nofollow\"  rel=\"external
      nofollow\" ?>\n    <configuration>\n        <property>\n            <name>fs.defaultFS</name>\n
      \           <value>hdfs://hdfs-master.hadoop:9000</value>\n        </property>\n
      \       <property>\n            <name>dfs.namenode.rpc-bind-host</name>\n            <value>0.0.0.0</value>\n
      \       </property>\n        <property>\n\t  <name>hadoop.security.token.service.use_ip</name>\n\t
      \ <value>false</value>\n\t</property>\n        <property>\n          <name>hadoop.http.staticuser.user</name>\n
      \         <value>root</value>\n        </property>\n        <property>\n          <name>hadoop.proxyuser.root.groups</name>\n
      \         <value>*</value>\n        </property>\n        <property>\n          <name>hadoop.proxyuser.root.hosts</name>\n
      \         <value>*</value>\n        </property>\n        <property>\n          <name>net.topology.script.file.name</name>\n
      \         <value>/opt/hadoop/etc/hadoop/rack_topology.sh</value>\n        </property>\n
      \   </configuration>"
    hdfs-site.xml: |-
      <?xml version="1.0" encoding="UTF-8"?>
          <?xml-stylesheet type="text/xsl" href="configuration.xsl" rel="external nofollow"  rel="external nofollow" ?>
          <configuration>
              <property>
                  <name>dfs.namenode.http-address</name>
                  <value>0.0.0.0:9870</value>
              </property>
              <property>
                  <name>dfs.namenode.name.dir</name>
                  <value>file:///opt/hadoop/hdfs/name</value>
              </property>
              <property>
                  <name>dfs.datanode.data.dir</name>
                  <value>file:///opt/hadoop/hdfs/data</value>
              </property>
              <property>
                  <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
                  <value>false</value>
              </property>
              <property>
                  <name>dfs.replication</name>
                  <value>3</value>
              </property>
              <property>
                <name>dfs.permissions</name>
                <value>false</value>
              </property>
          </configuration>
  kind: ConfigMap
  metadata:
    name: hadoop-conf
    namespace: hive
- apiVersion: v1
  data:
    hive-env.sh: export HADOOP_HEAPSIZE=1024
    hive-site.xml: |-
      <?xml version="1.0" encoding="UTF-8" standalone="no"?>
          <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
          <configuration>
            <property>
              <name>hive.execution.engine</name>
              <value>mr</value>
            </property>
            <property>
              <name>hive.metastore.uris</name>
              <value>thrift://metastore:9083</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionUserName</name>
              <value>root</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionPassword</name>
              <value>123456</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionURL</name>
              <value>jdbc:mysql://mysql8.mysql:3306/hive?useSSL=false&amp;useAffectedRows=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;serverTimezone=Asia/Shanghai&amp;allowMultiQueries=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=UTF-8&amp;allowPublicKeyRetrieval=true</value>
            </property>
            <property>
             <name>hive.aux.jars.path</name>
             <value>file:///opt/hive/lib/libfb303-0.9.3.jar,file:///opt/hive/lib/iceberg-hive-runtime-0.13.2.jar</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionDriverName</name>
              <value>com.mysql.cj.jdbc.Driver</value>
            </property>
            <property>
              <name>datanucleus.autoCreateTables</name>
              <value>True</value>
            </property>
            <property>
              <name>hive.metastore.warehouse.dir</name>
              <value>hdfs://hdfs-master.hadoop:9000/user/hive/warehouse</value>
            </property>
            <property>
              <name>hive.metastore.schema.verification</name>
              <value>false</value>
            </property>
            <property>
               <name>hive.metastore.event.db.notification.api.auth</name>
               <value>false</value>
            </property>
            <property>
               <name>iceberg.engine.hive.enabled</name>
               <value>true</value>
            </property>
          </configuration>
  kind: ConfigMap
  metadata:
    name: hive-conf
    namespace: hive
- apiVersion: v1
  data:
    configuration.yaml: |-
      linux:
        host: 192.168.3.204
        port: 22
        username: root
        password: '123456'

      mysql:
        host: mysql8.mysql
        port: 3306
        database: hive
        username: root
        password: '123456'
  kind: ConfigMap
  metadata:
    name: lockclean-conf
    namespace: hive
kind: List
metadata:
  resourceVersion: ""
