apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: hiveserver2
      workload.user.cattle.io/workloadselector: apps.deployment-hive-hiveserver2
    name: hiveserver2
    namespace: hive
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-hive-hiveserver2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-hive-hiveserver2
      spec:
        affinity: {}
        containers:
        - env:
          - name: NODE_TYPE
            value: hiveserver2
          image: 192.168.10.101:5000/hive-3.3.4:3.1.2
          imagePullPolicy: Always
          name: container-0
          ports:
          - containerPort: 10000
            name: hiveserver2
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hive/conf/hive-site.xml
            name: vol-hive-conf
            subPath: hive-site.xml
          - mountPath: /opt/hive/conf/hive-env.sh
            name: vol-hive-conf
            subPath: hive-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-hadoop-conf
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-hadoop-conf
            subPath: hdfs-site.xml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hive-conf
          name: vol-hive-conf
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-hadoop-conf
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-hive-metastore
    name: metastore
    namespace: hive
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-hive-metastore
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-hive-metastore
      spec:
        affinity: {}
        containers:
        - env:
          - name: NODE_TYPE
            value: metastore
          image: 192.168.10.101:5000/hive-3.3.4:3.1.2
          imagePullPolicy: Always
          name: container-0
          ports:
          - containerPort: 9083
            name: metastore
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hive/conf/hive-site.xml
            name: vol-hive-conf
            subPath: hive-site.xml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hive-conf
          name: vol-hive-conf
        - configMap:
            defaultMode: 420
            name: lockclean-conf
          name: vol-lockclean-conf
kind: List
