apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: hiveserver2
    namespace: hive
  spec:
    ports:
    - name: hiveserver2
      port: 10000
      protocol: TCP
      targetPort: 10000
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-hive-hiveserver2
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: metastore
    namespace: hive
  spec:
    ports:
    - name: metastore
      port: 9083
      protocol: TCP
      targetPort: 9083
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-hive-metastore
    sessionAffinity: None
    type: ClusterIP
kind: List
