apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "29"
      field.cattle.io/description: hdfs-master
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.3.204"],"port":30900,"protocol":"TCP","serviceName":"hadoop:hdfs-master-nodeport","allNodes":true},{"addresses":["192.168.3.204"],"port":30987,"protocol":"TCP","serviceName":"hadoop:hdfs-master-nodeport","allNodes":true}]'
    creationTimestamp: "2022-12-19T06:27:28Z"
    generation: 33
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-hadoop-hdfs-master
    name: hdfs-master
    namespace: hadoop
    resourceVersion: "15402177"
    uid: ef1be25a-d48b-448d-9102-db28290ba106
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-hadoop-hdfs-master
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2023-01-28T06:49:21Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-hadoop-hdfs-master
      spec:
        affinity: {}
        containers:
        - env:
          - name: HADOOP_NODE_TYPE
            value: namenode
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                key: HDFS_MASTER_SERVICE
                name: hadoop-conf
                optional: false
          - name: HDOOP_YARN_MASTER
            valueFrom:
              configMapKeyRef:
                key: HDOOP_YARN_MASTER
                name: hadoop-conf
                optional: false
          image: 192.168.10.101:5000/hadoop:3.3.4
          imagePullPolicy: Always
          name: container-0
          ports:
          - containerPort: 9000
            name: default-fs
            protocol: TCP
          - containerPort: 9870
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/hadoop-env.sh
            name: vol-cxwnc
            subPath: hadoop-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-cxwnc
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-cxwnc
            subPath: hdfs-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            name: vol-cxwnc
            subPath: yarn-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/rack_topology.data
            name: vol-cxwnc
            subPath: rack_topology.data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-cxwnc
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-19T06:27:28Z"
      lastUpdateTime: "2023-02-01T06:31:47Z"
      message: ReplicaSet "hdfs-master-6d99ccb67b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-02-23T04:57:27Z"
      lastUpdateTime: "2023-02-23T04:57:27Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 33
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "15"
      field.cattle.io/description: yarn-master
      field.cattle.io/publicEndpoints: '[{"addresses":["192.168.3.204"],"port":32088,"protocol":"TCP","serviceName":"hadoop:yarn-master-nodeport","allNodes":true}]'
    creationTimestamp: "2022-12-19T06:17:25Z"
    generation: 16
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-hadoop-yarn-master
    name: yarn-master
    namespace: hadoop
    resourceVersion: "15402256"
    uid: 8ea28ba8-91b5-4277-a2d9-d27e6edbdf58
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-hadoop-yarn-master
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2023-01-09T06:34:00Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-hadoop-yarn-master
      spec:
        affinity: {}
        containers:
        - env:
          - name: HADOOP_NODE_TYPE
            value: resourceman
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                key: HDFS_MASTER_SERVICE
                name: hadoop-conf
                optional: false
          - name: HDOOP_YARN_MASTER
            valueFrom:
              configMapKeyRef:
                key: HDOOP_YARN_MASTER
                name: hadoop-conf
                optional: false
          image: 192.168.10.101:5000/hadoop:3.3.4
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 8031
            name: ipc1
            protocol: TCP
          - containerPort: 8033
            name: ipc2
            protocol: TCP
          - containerPort: 8088
            name: http
            protocol: TCP
          - containerPort: 8032
            name: rm-asm
            protocol: TCP
          - containerPort: 8030
            name: ipc-scheduler
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/hadoop-env.sh
            name: vol-qllya
            subPath: hadoop-env.sh
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: vol-qllya
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: vol-qllya
            subPath: hdfs-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            name: vol-qllya
            subPath: yarn-site.xml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: hadoop-conf
          name: vol-qllya
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-19T06:17:25Z"
      lastUpdateTime: "2023-01-09T06:34:02Z"
      message: ReplicaSet "yarn-master-565f7f4c7f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-02-23T04:57:32Z"
      lastUpdateTime: "2023-02-23T04:57:32Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 16
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
