apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zookeeper
    namespace: zookeeper
  spec:
    ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-zookeeper-zookeeper
    sessionAffinity: None
    type: ClusterIP
kind: List
