apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "51"
      field.cattle.io/publicEndpoints: "null"
    creationTimestamp: "2022-12-27T07:45:25Z"
    generation: 64
    labels:
      app: presto
      workload.user.cattle.io/workloadselector: apps.deployment-presto-presto
    name: presto
    namespace: presto
    resourceVersion: "15442331"
    uid: b13ef396-0dba-4b3b-a35b-31fbe52d48f7
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-presto-presto
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2023-02-21T07:35:39Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-presto-presto
      spec:
        affinity:
          podAffinity: {}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - hiveserver2
                namespaces:
                - presto
                - hive
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - image: ahanaio/prestodb-sandbox:0.278.1
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
          - containerPort: 8091
            name: presto
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/presto-server/etc/catalog/hive.properties
            name: vol-5fmjl
            subPath: hive.properties
          - mountPath: /opt/presto-server/etc/catalog/iceberg.properties
            name: vol-5fmjl
            subPath: iceberg.properties
          - mountPath: /opt/presto-server/etc/catalog/mysql.properties
            name: vol-5fmjl
            subPath: mysql.properties
          - mountPath: /opt/presto-server/etc/config.properties
            name: vol-yunlc
            subPath: config.properties
          - mountPath: /opt/presto-server/etc/jvm.config
            name: vol-yunlc
            subPath: jvm.config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: presto-hadoop-conf
          name: vol-iuhwu
        - configMap:
            defaultMode: 420
            name: presto-catalog-conf
          name: vol-5fmjl
        - configMap:
            defaultMode: 420
            name: presto-conf
          name: vol-yunlc
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-27T07:45:25Z"
      lastUpdateTime: "2023-02-21T07:36:03Z"
      message: ReplicaSet "presto-78dff89899" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-02-23T09:11:53Z"
      lastUpdateTime: "2023-02-23T09:11:53Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 64
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
