apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/targetWorkloadIds: '["zookeeper/zookeeper"]'
      management.cattle.io/ui-managed: "true"
    creationTimestamp: "2022-12-16T08:44:31Z"
    name: zookeeper
    namespace: zookeeper
    ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: zookeeper
      uid: 72712ffe-b34c-4917-a798-db266a4a96aa
    resourceVersion: "3816258"
    uid: b49307d0-0a5d-4b02-b1a8-08bcbf832628
  spec:
    clusterIP: 10.43.180.212
    clusterIPs:
    - 10.43.180.212
    externalIPs:
    - 192.168.3.204
    ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-zookeeper-zookeeper
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
